import { useQuery } from '@tanstack/react-query';
import { CircleCheck, Mail } from 'lucide-react';
import { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { fmtDateTime } from '../../shared/format';
import { FormStatusBadge } from '../components/ui/Badge';
import { Button } from '../components/ui/Button';
import { CheckCard, Field, TextInput } from '../components/ui/Controls';
import { ErrorState, InfoNote, PageHeader, Skeleton } from '../components/ui/Layout';
import { Modal } from '../components/ui/Overlay';
import { useToast } from '../components/ui/Toast';
import { api, download } from '../lib/api';
import { useAuth } from '../lib/auth';
import { errorMessage } from '../lib/query';
import type { FormDetail } from '../lib/formTypes';

const SUB: Record<string, string> = {
  ISSUANCE: 'Issuance & indemnity (Form 2) - recipient signed by email, IT recorded as issuer',
  INDEMNITY: 'Issuance & indemnity (Form 2) - generated by a movement, IT recorded as issuer',
  RETURN: 'Return (Form 4) - returner confirmed by email, IT recorded as receiver',
  MOVEMENT: 'Movement (Form 3) - approved by CTO and Admin Officer, parties confirmed by email',
};

/** Signed document preview (AB-12). The iframe shows the exact HTML used for the PDF. */
export function DocumentPage() {
  const { reference = '' } = useParams();
  const navigate = useNavigate();
  const toast = useToast();
  const [copy, setCopy] = useState(false);
  const form = useQuery({ queryKey: ['form', 'ref', reference], queryFn: () => api<FormDetail>(`/forms/by-ref/${reference}`) });
  const html = useQuery({
    queryKey: ['form-html', form.data?.id, form.data?.status],
    queryFn: () => api<{ html: string }>(`/forms/${form.data!.id}/document`),
    enabled: !!form.data,
  });
  const f = form.data;
  const signer = f?.parties.find((p) => p.needsSignature && p.status === 'SIGNED');
  const signed = f?.status === 'SIGNED';

  return (
    <>
      <PageHeader
        back={{ label: 'Back', onClick: () => (window.history.length > 1 ? navigate(-1) : navigate('/signoffs')) }}
        title={f ? `${f.reference} · ${signed ? 'Signed' : f.status === 'PENDING_APPROVAL' ? 'Awaiting approval' : f.status.charAt(0) + f.status.slice(1).toLowerCase()}` : reference}
        subtitle={f ? SUB[f.type] : undefined}
        actions={
          f ? (
            <>
              <Button variant="secondary" size="lg" className="min-w-[170px]" onClick={() => download(`/forms/${f.id}/pdf`, `ECEWS-ITAMS-${f.reference}.pdf`).catch((e) => toast.error(errorMessage(e)))}>
                Download PDF
              </Button>
              <Button variant="outline" size="sm" icon={<Mail className="h-4 w-4" />} onClick={() => setCopy(true)}>
                Email copy
              </Button>
            </>
          ) : null
        }
      />
      {f ? (
        <div className="-mt-2 mb-5 flex flex-wrap items-center gap-3">
          {signed && signer ? (
            <span className="inline-flex items-center gap-1.5 rounded-pill bg-green-100 px-3 py-1 text-sm font-semibold text-brand">
              <CircleCheck className="h-4 w-4" aria-hidden />
              Signature verified · {fmtDateTime(signer.signedAt)} WAT{signer.ipAddress ? ` · IP ${signer.ipAddress}` : ''}
            </span>
          ) : null}
          <FormStatusBadge status={f.status} />
          <span className="text-sm text-gray-500">
            {signed ? 'One-time link · opened once · session recorded' : 'Preview — the document is not yet fully signed'}
          </span>
        </div>
      ) : null}
      <div className="rounded-md bg-canvas px-2 py-6 sm:px-6">
        {form.error ? (
          <ErrorState message={errorMessage(form.error)} onRetry={() => void form.refetch()} />
        ) : html.data ? (
          <iframe
            title={`${reference} document`}
            srcDoc={html.data.html}
            sandbox=""
            className="mx-auto block h-[1123px] w-full max-w-[794px] bg-white shadow-2"
          />
        ) : (
          <div className="mx-auto max-w-[794px] space-y-3 bg-white p-12">
            <Skeleton className="h-8 w-60" />
            <Skeleton className="w-full" />
            <Skeleton className="w-3/4" />
          </div>
        )}
      </div>
      {f ? <EmailCopyModal form={f} open={copy} onOpenChange={setCopy} /> : null}
    </>
  );
}

function EmailCopyModal({ form, open, onOpenChange }: { form: FormDetail; open: boolean; onOpenChange: (v: boolean) => void }) {
  const { user } = useAuth();
  const toast = useToast();
  const signer = form.parties.find((p) => p.needsSignature && p.email);
  const [to, setTo] = useState(user?.email ?? '');
  const [also, setAlso] = useState(true);
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);
  return (
    <Modal
      open={open}
      onOpenChange={onOpenChange}
      title="Email copy"
      subtitle={`${form.reference}${form.completedAt ? ` · Signed ${fmtDateTime(form.completedAt)} WAT` : ''}`}
      footer={
        <>
          <Button variant="outline" size="lg" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button
            size="lg"
            loading={busy}
            icon={<Mail className="h-4 w-4" />}
            onClick={async () => {
              if (!/^\S+@\S+\.\S+$/.test(to)) return setErr('Enter a valid email address.');
              setBusy(true);
              try {
                const r = await api<{ sentTo: string[]; emailWarning: string | null }>(`/forms/${form.id}/email-copy`, { body: { to, alsoSigner: also && !!signer } });
                if (r.sentTo.length) toast.success(`Copy of ${form.reference} sent to ${r.sentTo.join(', ')}`);
                if (r.emailWarning) toast.error(r.emailWarning);
                onOpenChange(false);
              } catch (e) {
                toast.error(errorMessage(e));
              } finally {
                setBusy(false);
              }
            }}
          >
            Send copy
          </Button>
        </>
      }
    >
      <div className="space-y-4">
        <Field label="Send copy to" htmlFor="copy-to" error={err ?? undefined}>
          <TextInput id="copy-to" type="email" value={to} onChange={(e) => (setTo(e.target.value), setErr(null))} />
        </Field>
        {signer ? (
          <CheckCard
            checked={also}
            onCheckedChange={setAlso}
            title="Also email the signer"
            description={`${signer.name} · ${signer.email} receives the same PDF.`}
          />
        ) : null}
        <InfoNote icon={Mail}>The PDF is regenerated from the same record — screen, printout and email copy can never disagree.</InfoNote>
      </div>
    </Modal>
  );
}
